name: auto deb
on: 
  push: 
    branches:  [ main ]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: add execute mode
        run: chmod +x make-deb/usr/bin/hello

      - name: 安装依赖包
        run: sudo apt update && sudo apt install dpkg-dev -y

      - name: 打包deb
        run: dpkg-deb --build make-deb

      - name: 列出打包结果
        run: ls -lh make-deb.deb
      
      - name: 上传deb包
        uses: actions/upload-artifact@v4
        with:
          name: make-deb-package
          path: make-deb.deb


